### ISSUE TITLE
Javascript-bound event loop makes laptop fans go crazy

### ISSUE THREAD

**Issue by johan** [malsup/cycle#1]
Doing setTimeout (or setInterval) based animation tends to get laptops at rather high CPU usage so fans go on for their duty cycle on http://www.malsup.com/jquery/cycle/, or even for a basic fade $('#movie').cycle(); like at http://mashlogic.com/.

Have you considered doing the animations in SMIL (http://www.w3.org/TR/SMIL2/ -- an open standard backed by the W3C, widely supported and implemented in all the major modern browsers)? That shoves the resource critical loop out of javascript space, where it doesn't boost CPU usage.

(The Fade example at the end of http://u.nu/86u8 exemplifies the difference between declarative animation and imperative code, where that page isn't measurably cpu bound, or at least not on the same order of magnitude as jQuery Cycle is.)

**Comment by malsup** [comment]
Definitely not considering this change any time soon.  With the exception of the "wipe" transition, the Cycle plugin does not explicitly use setTimeout for the animation.  Rather, it uses setTimeout to control when animations should start and then invokes jQuery's "animate" function for the effect.  Of course, "animate" does use setInterval to manage the property changes.  But right now Cycle is written to rely on the underlying core library for the effects.

**Comment by johan** [comment]
Ah -- thanks for sending me in the right direction!
