### ISSUE TITLE
cycle('destroy') does not clean up the cycleStop property

### ISSUE THREAD

**Issue by biziclop** [malsup/cycle#108]
After creating, destroying and recreating a cycle with the same parameters, cycling stops after the first transition:

``` javascript
$featured_content.cycle( opts1 ); // looping is okay
$featured_content.cycle('destroy');
$featured_content.cycle( opts2 ); // loop stops after one transition
```

Adding one line to the $.fn.cycle function seems to fix the bug:

``` javascript
$.fn.cycle = function(options, arg2) {
  ..
  this.cycleTimeout = this.cyclePause = 0;
  this.cycleStop = 0; // this was ==1  in the second creation
```

I found this similar problem on StackOverflow:
http://stackoverflow.com/questions/9025354/jquery-cycle-destroyed-a-cycle-with-autostop-restarted-it-now-it-stops-on-t

**Comment by malsup** [comment]
Thanks.
