### ISSUE TITLE
Metadata Demo does not appear to work with later versions of the plugin

### ISSUE THREAD

**Issue by bullarni** [malsup/cycle#109]
I was trying to implement the jQuery cycle plugin using the meta-data method shown on the malsup site.
http://malsup.com/jquery/cycle/meta.html

I had downloaded the latest version of the plugin but could not get the "data-cycle" attribute method to work. I saved the Metadata Demo locally to see if it would work and it did. Then I replaced the cycle JavaScript in the demo with later versions of the plugin from github and none of them worked.

Am I missing something or is the meta-data method not supported any more?

**Comment by malsup** [comment]
That demo is using the latest version of cycle.  Support for data-cycle has not been removed.

**Comment by bullarni** [comment]
Are you sure the files are the same?

Demo downloaded as is and the cylce works as expected:
http://_testbed.bkel.platform.local/stuff/test1.cfm

Replace the cycle js with jquery.cycle.all.latest.min.js from github and the cycle reverts to default settings:
http://_testbed.bkel.platform.local/stuff/test2.cfm

I tried with all the non-lite cycle versions available at https://github.com/malsup/cycle/downloads without success. The only way I could get my code to regard the data-cycle attribute was to download the plugin version available at http://malsup.github.com/jquery.cycle.all.js

Could you please let me know where I am going wrong. Thanks.

**Comment by malsup** [comment]
This is the latest version:

http://malsup.github.com/jquery.cycle.all.js

Everything at https://github.com/malsup/cycle/downloads is old.  In fact, that page mentions that they were uploaded two years ago.  Sorry for the confusion.  I'd delete those files under downloads but don't want to break sites that are linking to them.

The README at https://github.com/malsup/cycle has a valid link.

**Comment by bullarni** [comment]
Fair enough. Thanks for the clarification. Understandable to leave them there to prevent breaking sites, just unfortunate that one of them is labelled latest. Great Plugin BTW.
