### ISSUE TITLE
disabledPrevNextClass when nowrap, prev and next links used

### ISSUE THREAD

**Issue by ErickPetru** [malsup/cycle#11]
When we set nowrap to true and assign prev and/or next links, the prev don't run when currSlide is 0 and next don't run when currSlide is slideCount. Pretty fine.

But, if a button will not perform any action, this button would be displayed with any change, like a disabled state, wich is good to usability.

I had changed the Cycle code here to obtain this need, creating two new options: disabledPrevNextClass (with the default value "disabledSlide") and updatePrevNextLink with a "callback fn invoked to update prev and next links if it are disabled or not (adds/removes disabledPrevNextClass style)".

I think this feature is very important with the nowrap scenario.

PS.: If you want to see my complete code, you are welcome.

**Comment by malsup** [comment]
FYI, you can also achieve this using the after callback:

```
$('#slideshow').cycle({
    prev: '#prev',
    next: '#next',
    after: function(curr, next, opts) {
        var first = opts.currSlide == 0;
        var last =  opts.currSlide == (opts.slideCount - 1);
        $(opts.prev)[first ? 'addClass' : 'removeClass']('disabledSlide');
        $(opts.next)[last  ? 'addClass' : 'removeClass']('disabledSlide');
    }
});
```

**Comment by ErickPetru** [comment]
Damn, I tried this solution much before changing the source code of the plugin.
Should have looked better. Lol.

Anyway, I believe this class automatically applied in the case of nowrap would be very useful to enough people. Despite increasing (slightly) the size of the plugin. Anyway, the idea is recorded.

**Comment by ErickPetru** [comment]
Since this can be achieved using "after" I'm closing because there is no "issue". I appreciate the help and the idea is recorded if you consider interesting for the future. Thanks.
