### ISSUE TITLE
.currSlide isn't being executed correctly when fx: 'fadeout'

### ISSUE THREAD

**Issue by albell** [malsup/cycle#111]
I'm building a slideshow using fx: 'fadeout'.  (I like its transition effect better, because no background ever shows through.) It works fine. I'm using cycle lite 1.5.

But I've added an image counter following the pattern here:

http://jquery.malsup.com/cycle/count.html

and the currSlide function is acting very strangely. When I click forward to the second slide, the image changes, but the counter stays at the number 1. When I click a second time, then the counter and image both advance, but the count is off by one. Then everything works correctly as I click through the slideshow (though the count continues to be off by one).

Similarly, when I'm in the middle of the slideshow, when I click the "previous" button, the currSlide count actually increases by one (!!! instead of decreasing). On the second and subsequent "previous" clicks, the counter decrements correctly.

None of this behavior happens with the default fx: 'fade'. I imagine that this is because of the unique "top" and "bottom" threading pattern with 'fadeout'. Any ideas how to work around this?

Thanks in advance!

**Comment by malsup** [comment]
Fixed.  Thanks for the detailed report.
