### ISSUE TITLE
Image disappeared in IE8

### ISSUE THREAD

**Issue by vinumsc** [malsup/cycle#116]
The cycle plugin works fine except IE.... In IE8, it displays nothing after one slide was animated....Next second slide comes after some interval... The interval is the same time of slide transition time... It happened for every slides and effects.... Can anybody please tell me how to solve this?

**Comment by malsup** [comment]
Please provide a link to a test page that exhibits the problem.

**Comment by vinumsc** [comment]
Hi Malsup, Please check this bug in http://hotel.sparklegroups.com..... Here the banner animation i have used jquery easing and cycle plugin. It not works fine in IE8... Can you please check it and give the solution..?

I also checked in IE6 and there is also same problem

**Comment by malsup** [comment]
That page has bad markup.  Remove all of the `</img>` tags, they are not valid and they cause IE to insert empty elements.

**Comment by vinumsc** [comment]
Thanks Malsup... It works fine now...

**Comment by crazykane2000** [comment]
Hey Malsup,

dear im stuck out with a great problem Cycle plugin is not at all working in ie i dont know what the problem is but i checked the zindex, trailling commas, class to id concept and all solution i got from google but still i havent got any good solution, The slideshow is working fine on other browser but not in ie please do help..

Thanks in advance.

**Comment by crazykane2000** [comment]
http://catpops.in/webnext/ it is the link try opening in ie7,8,6,9 the problem persist in all IE

**Comment by malsup** [comment]
I guess you fixed this because it seems to be working fine.

**Comment by crazykane2000** [comment]
Dear Sir,

Yeah I Have Fixed It sorry I disturbed you, actually it was Minor bug of
IE, The z-index stacking problem It got solved,

Thanks again

Kishan Sharma
