### ISSUE TITLE
Manually advance to next/previous slide?

### ISSUE THREAD

**Issue by reado83** [malsup/cycle#119]
I have a slideshow cycling on an infinite loop but would like to introduce a pause-on-hover ability so that when someone hovers over the slideshow, it stops cycling. I would also like to add next and previous buttons so they can advance the slideshow themselves.

Any help would be greatly appreciated.

**Comment by malsup** [comment]
Pause on hover is achieved via the 'pause' option:  
http://jquery.malsup.com/cycle/begin.html

Prev/Next capabilities leverage the 'prev' and 'next' options:
http://jquery.malsup.com/cycle/int2.html

**Comment by reado83** [comment]
Just found this: http://jquery.malsup.com/cycle/pause.html

Thanks for your help. Much appreciated. :-)
