### ISSUE TITLE
Feature Idea - set options with data attributes

### ISSUE THREAD

**Issue by jakemac53** [malsup/cycle#121]
I was thinking it would be really cool if you could use data attributes on your slideshow elements to set the options. Then you could use a general selector like $(".slideshow").cycle(); to run a slideshow on all elements with that class, and customize it on a per slideshow basis without having to add additional javascript. For example to set the effect, speed, and timeout it would look like the following:

``` html
<div class="slideshow" data-fx="shuffle" data-speed="1000" data-timeout="4000">
```

This would be really nice when working within cms systems where you would have to go into the template to add javascript (since most editors won't allow it). You could instead have the one generic slideshow definition and set the options on a per-slideshow basis very easily.

Thoughts?

**Comment by malsup** [comment]
There is support for something similar:  http://jquery.malsup.com/cycle/meta.html

**Comment by jakemac53** [comment]
Oh nice! I never new this existed and it does effectively the same thing, probably better actually since it uses just one data attribute thats less likely to conflict with anything else.
