### ISSUE TITLE
previous button not working.

### ISSUE THREAD

**Issue by OldNick** [malsup/cycle#123]
I'm using the latest version of jquery.cycle.all.js and I don't seem to be able to get the "previous" function to work.

In the setup of the slideshow I have
next :'#next',
previous: "#prev',

These link to divs either side of the slideshow. The "Next" button works as expected, but I get no response from the "previous" one.
Is it something I'm doing or is there a bug somewhere.

**Comment by malsup** [comment]
It's probably something you're doing in the markup.  Could that #prev div be beneath another element?

**Comment by OldNick** [comment]
I've just checked - it's on the same level as the "next" div, and 
identical with it, but with attributes changed - here's the markup, 
sorry about all the php, it's for a slideshow I'm doing in wordpress.

```
<div id="prev" class="control"> <i class="icon-chevron-left"></i> </div>

     <div id="projection">

        <?php foreach ($galleries as $gallery) : ?>

           <div class="slide">

                <a class="gall-link" href="<?php echo $gallery->pagelink ?>" title="<?php echo $gallery->title ?>">

                    <img alt="<?php echo $gallery->title ?>" src="<?php echo $gallery->path.'/'.$gallery->previewname ?>"/>

                </a>

                <p class="gall-descrip">

                <span class="gall-title"><?php echo $gallery->title ?>

                </span>

                <br />

              <?php echo nggcf_get_gallery_field($gallery->gid, "Short description"); ?>

                </p>

        </div>

         <?php endforeach; ?>

        </div>

        <div id="next" class="control"> <i class="icon-chevron-right"></i> </div>
```

**Comment by malsup** [comment]
Ah, this:

```
previous: "#prev',
```

should be this:

```
prev: "#prev',
```

**Comment by OldNick** [comment]
God I'm stupid ! It's there in black and white.
Thanks for your help - I've rather wasted your time.

**Comment by malsup** [comment]
No worries.
