### ISSUE TITLE
Seems doesn't work with jquery 1.8.0

### ISSUE THREAD

**Issue by timotheemoulin** [malsup/cycle#125]
Hi,
I'm running on Drupal 7 with jQuery 1.8.0 and the plugin doesn't work.
I get the following message :
[cycle] terminating; too few slides: 1

but I have always 2 or 3 slides to show

**Comment by malsup** [comment]
Can you post a link?  There is likely something wrong with the markup that is causing cycle to find only one slide.

**Comment by timotheemoulin** [comment]
I just replace the query library with the 1.7.2 version and all works as
well

Cdlt,

Timothée Moulin

Tous les jours, il faut lutter pour que cet amour de l'humanité vivante se
transforme en gestes concrets, en gestes qui servent d'exemple et qui
mobilisent.
Ernesto Guevara

Timothée Moulin
Technicien ES - WEB
timothee@tehem.ch
079 265 16 68

From:  Mike Alsup notifications@github.com
Reply-To:  malsup/cycle
<reply+i-6548761-a1554fed73d995413dfae7bc6a999c3d809c7ff6-1841590@reply.gith
ub.com>
Date:  Thu, 30 Aug 2012 06:45:22 -0700
To:  malsup/cycle cycle@noreply.github.com
Cc:  Timothee Moulin timothee.moulin@gmail.com
Subject:  Re: [cycle] Seems doesn't work with jquery 1.8.0 (#125)

Can you post a link?  There is likely something wrong with the markup that
is causing cycle to find only one slide.

 ‹
 Reply to this email directly or view it on GitHub
https://github.com/malsup/cycle/issues/125#issuecomment-8159763 .

**Comment by florin-bombeanu** [comment]
It seems to work for me with both 1.8.0 and 1.8.1 on a simple example.

**Comment by Lux-Delux** [comment]
Hello, I'm having the same problem. Works fine with lower jquery versions but not with latest.

I left it on the front page in case it can give you some insight (Lux Recommended Content Picks!)
http://www.bad-good.org/

Cheers

**Comment by malsup** [comment]
It's not Cycle.  Look at the stack trace when cycle is invoked.  It looks to be something with the image loader script.
