### ISSUE TITLE
After opts.currSlide error when fx:none

### ISSUE THREAD

**Issue by dotnetshadow** [malsup/cycle#13]
Hi there,

I think there is a bug with cycle when the fx is none the opts.currIndex doesn't get updated properly on after event. What happens is that the index in the after event remains 0 for the first 2 times then it increments properly. Check the code below:

```
        function onAfter(curr, next, opts) {                               
            var caption = (opts.currSlide + 1) + ' / ' + opts.slideCount;
            $('#caption').html(caption);
        }

        $('#tips').cycle({
            fx: 'fade',
            next: '#next',
            prev: '#prev',
            startingSlide: 0,
            timeout: 5000,
            after: onAfter
        });
```

Regards DotnetShadow

**Comment by mattiasj** [comment]
Hi,

I can confirm this bug when working with the same scenario. I need this functionality so I would be glad to help and test if a patch gets available. For now I use fx: fade with the shortest time but it doesn't get me the effect i need.

Regards
Mattias

**Comment by malsup** [comment]
Pretty sure this has been fixed.  Demo: http://jquery.malsup.com/cycle/none4.html
