### ISSUE TITLE
Before and after callbacks are fired on initial load

### ISSUE THREAD

**Issue by jahvi** [malsup/cycle#132]
They work fine after though but shouldn't they be fired right "before" or "after" a slide transition only?

See [JS Fiddle](http://jsfiddle.net/vengiss/gshtZ/4/) for an example.

**Comment by malsup** [comment]
They are fired artificially during slideshow initialization so that callbacks can set initial state.  There are pros and cons to doing it this way, but it's been part of the API for a long time and is too late to change.  Cycle2 does not do this.

**Comment by jahvi** [comment]
I see, is there even a hacky way to prevent this? I kind of need a workaround for a project I'm finishing up :cry:

**Comment by malsup** [comment]
I had forgotten about this option:  skipInitializationCallbacks

Set to true to avoid those callbacks.

**Comment by jahvi** [comment]
Thanks that worked fine
