### ISSUE TITLE
jQuery 1.9 has removed $.browser which now crashes the plugin

### ISSUE THREAD

**Issue by matthewbuchanan** [malsup/cycle#136]
Suggest using some other form of UA sniffing?

**Comment by matthewbuchanan** [comment]
This patch works:

/_Browser detection patch_/
$.browser = {};
$.browser.msie = /msie/.test(navigator.userAgent.toLowerCase());

**Comment by marcogrimaldi85** [comment]
Thanks, it's important to fix on cycle this bug
