### ISSUE TITLE
Cycle Plugin doesn't work with multiple slideshows in IE8

### ISSUE THREAD

**Issue by ghost** [malsup/cycle#138]
hello mike,
i have a problem with your plugin. 
it works fine in all of the browsers, but i have serious trouble to get it going with IE8.

the page contains 2 slideshows. and now the fun part: the lower slideshow is working. but the upper one doesnt. (only in IE8)

these are the function calls:

```
  window.onDomReady(onReady);
  function onReady(){
    jQuery('#slidervar').cycle({
      fx: 'fade',   
      activePagerClass: 'active',
      next:   '#backpage', 
      prev:   '#nextpage',         
      speed:  700, 
      timeout: 0     
    });
  }

  window.onDomReady(onReady);
  function onReady(){
    jQuery('#slidervar2').cycle({
      fx: 'fade',   
      activePagerClass: 'active2',
      next:   '#backpage2', 
      prev:   '#nextpage2',
      startingSlide: 1,
      speed:  700, 
      timeout: 0              
  });
  }
```

as you can see, i used different id's on every container. 

in the output of the first slideshow the images are all visible and the click event is not firing. the second one works fine.

do you have any idea what to do?

i appreciate your work and would be very happy to hear from you soon :)

best regards, 
michael

ps: sorry about my english, i am not a native speaker ;)

**Comment by malsup** [comment]
Why do you have two functions with the same name?

**Comment by ghost** [comment]
that's a good question :) i'm loading 2 different templates, so i didn't realize that i'm probably overriding the method. i've changed it to:

 window.onDomReady(onReady);
  function onReady(){
    jQuery('#slidervar').cycle({
      fx: 'fade',  
      activePagerClass: 'active',
      next:   '#backpage', 
      prev:   '#nextpage',  
      speed:  700, 
      timeout: 0  
    });
  }

  window.onDomReady(onReady2);
  function onReady2(){
    jQuery('#slidervar2').cycle({
      fx: 'fade',  
      activePagerClass: 'active2',
      next:   '#backpage2', 
      prev:   '#nextpage2',
      startingSlide: 1,
      speed:  700, 
      timeout: 0  
  });
  }
but it still doesn't work in ie8. all other browser im testing in (chrome 20+, ff 17+) are unaffected and still working

ive googled a few issues about comma seperation problems in ie8 but i think i got that right. 
do you have any further recommendations?

edit: ive just browsed the code and i can see that the slider that's not working doenst't have any inline styles from the cycle.js as the other slider that is working

**Comment by malsup** [comment]
If you still need help, create a simplified demo and post a link, or use jsfiddle to create a simple demo that exhibits the problem.
