### ISSUE TITLE
jQuery dependency missmatch (documention vs. source)

### ISSUE THREAD

**Issue by ooxi** [malsup/cycle#139]
Hi,

while the [documentation](http://jquery.malsup.com/cycle/faq.html) states

> _What versions of jQuery is the Cycle Plugin compatible with?_
> The Cycle Plugin is compatible with jQuery v1.3.2 and later.

the [source](http://malsup.github.com/jquery.cycle.all.js) contains

> `Requires: jQuery v1.7.1 or later`

I'm using the jQuery Cycle Plugin with jQuery 1.3.2 without problems. I know, that [Cycle Lite](http://malsup.github.com/jquery.cycle.lite.js) explicitly requires only v1.3.2, but that difference should be reflected in the faq as well.

**Comment by malsup** [comment]
The plugin should work fine with jQuery 1.4+, but I'll only provide support for 1.7+.  Gotta keep with the times!  :-)
