### ISSUE TITLE
Images are smaller at first load

### ISSUE THREAD

**Issue by stijnbe** [malsup/cycle#14]
With version 2.88 the images are smaller at first load. When reloading the page and probably using the browser cache to load the images it's correct.

Stijnbe

**Comment by dotnetCarpenter** [comment]
I might have a connected issue. In webkit browsers the cycleH is always 37 the first time an image is shown but has the correct value second time around. I use the before event handler.

**Comment by malsup** [comment]
I don't know how to account for the browser placeholder images that are displayed before the image is loaded except to explicitly declare your image dimensions with width/height attributes (or in CSS).
