### ISSUE TITLE
Check if CYCLE is initialized

### ISSUE THREAD

**Issue by didoweb** [malsup/cycle#141]
Hi, I've got a question about checking if Cycle is initialized or not.

I've got a responsive site and I init Cycle on resize when the size is big than a value.
Before I do that, I want check if cycle is initialized yet. How I can do that?
This is the example:

if( $(window).width() > 767 && !$('myID').(CHECK CYCLE)  )

Thanks, Davide

**Comment by malsup** [comment]
You can test to see if Cycle's data object has been set on the slideshow object:

```
$('myId').data('cycle.opts') !== undefined
```

But for responsive slideshows you're much better off using Cycle2:

http://jquery.malsup.com/cycle2/

**Comment by didoweb** [comment]
Thanks a lot.

Davide
