### ISSUE TITLE
jquery.cycle.lite.1.7 cycle("next") doesnt go to next slide, but resumes the slideshow.

### ISSUE THREAD

**Issue by honk31** [malsup/cycle#143]
headline says it all. on 
$(elem).cycle("next");
the cycle lite version 1.7 resumes the slideshow with i dont know what settings (i have timeout: 0 and the slideshow moves on with something like timeout: 4000). but yeah, it moves on like somebody pressed "resume" but see for yourself:

$(".post").each(function() {
  $(this).find(".images").cycle({
    timeout: 0
  });
});
setInterval(function() {
  $(".post:eq(" + Math.floor(Math.random() \* $(".post").length) + ") .images").cycle("next");
}, 4000);

jquery.cycle.all.2.9999.81.js works as expected.

**Comment by malsup** [comment]
Cycle Lite does not support that feature.  It only supports the options show here:

http://jquery.malsup.com/cycle/lite/
