### ISSUE TITLE
It's possible make a link one image in one page to specific image in another page?

### ISSUE THREAD

**Issue by luis3** [malsup/cycle#144]
Hi,
It's possible have one page with thumb images and another page with a cycle animation, and when I click a thumb this image is linked with the same image in the second page? I have tried with anchor htm#img1 to id="img1" but he linked always in the same image the first of the cycle.
Can anybody please tell me how to solve this? Thanks in advance.

**Comment by malsup** [comment]
View the source of this page to understand how to set the startingSlide option based on the url:

http://jquery.malsup.com/cycle/perma.html

**Comment by luis3** [comment]
Hi Mike,

Thank you for your fast and precious help.  I have missed this page! I am a newbie anyway.
Congratulation for your great job.
