### ISSUE TITLE
containerResize does not work when page is zoomed

### ISSUE THREAD

**Issue by dolphprefect** [malsup/cycle#145]
Hello, 

when you zoom a website with ctrl+mousewheel and then refresh the page with a cycling element on it, which depends on containerResize, the container is resized to 0 height. I tested this with IE 10 and latest Firefox, probably an issue in Chrome too. I tracked down the problem to line 361:

``` javascript
var reshape = (opts.containerResize || opts.containerResizeHeight) && !$cont.innerHeight();
```

$cont.innerHeight() is not 0 with a zoomed page, but between 0 and 1. I fixed it changing the line to:

``` javascript
var reshape = (opts.containerResize || opts.containerResizeHeight) && $cont.innerHeight() < 1;
```

Best,
Dolph

**Comment by malsup** [comment]
Thanks!
