### ISSUE TITLE
Jquery slideshow not working

### ISSUE THREAD

**Issue by felix-ec** [malsup/cycle#152]
I’m sure is a slight little missing thing somewhere, but I’m not a programmer so I don’t know if, for example, the http://cloud.github.com/downloads/malsup/cycle/jquery.cycle.all.2.74.js has changed of location so that’s why the effect isn’t loading, or if there’s something new I should add to the effect’s code; if you could please take a look at the live page (http://www.galapagosnet.com/) to see how it displays and look at the code and let me know what’s wrong, I’ll really appreciate it. I’ve been looking over the Internet and couldn’t find why the images are loading like they are –originally the script worked just fine. Thanks for your time.

**Comment by malsup** [comment]
This link is no longer valid:  http://cloud.github.com/downloads/malsup/cycle/jquery.cycle.all.2.72.js

Please replace it with:

http://malsup.github.io/jquery.cycle.all.js

Or copy the plugin file to your local server and serve from there.

**Comment by leemcalilly** [comment]
I had a project using 2.74 and wasn't able to find this on github. If you need an old version you can also find it here:

https://code.google.com/p/enasis/source/browse/trunk/js/jquery.cycle.all.2.74.js?r=9

**Comment by codesigned** [comment]
And I upgraded to http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js from 1.3.2. Back in action. Thanks malsup and leemcalilly.
