### ISSUE TITLE
removing all slides

### ISSUE THREAD

**Issue by fgrs** [malsup/cycle#168]
is there a method in v2 to remove all slides at once?

**Comment by FibreFoX** [comment]
IMHO a simple solution could be to remove that slideshow entirely:

```
var targetSlideshow = $("#myTargetSlideshow");
targetSlideshow.cycle('destroy'); // dont leave events etc.
targetSlideshow.remove();
```

**Comment by fgrs** [comment]
yeah that's what I ended up doing but thought there might be better way replacing all the slides with new ones

**Comment by FibreFoX** [comment]
Let me try to get your idea (maybe it may be added as a new feature):
you want to have two "sets" of slideshow-images, right?

what do you want to reach with it? lazy-loading of images?
