### ISSUE TITLE
checkInstantResume opts.rev is undefined

### ISSUE THREAD

**Issue by tvanfosson** [malsup/cycle#18]
## Sorry didn't notice the existing report for this one.  I swear I looked for it first.

Ran into an error with player controls that resume a slide show.  In the function checkInstantResume, the following line:

```
go(options.elements, options, 1, (!opts.rev && !opts.backwards));
```

should be:

```
go(options.elements, options, 1, (!options.rev && !options.backwards));
```

**Comment by malsup** [comment]
No problem. This was fixed with the last commit.  I haven't had time to create a new release though.
