### ISSUE TITLE
Pager; activeslide not changing

### ISSUE THREAD

**Issue by ghost** [malsup/cycle#23]
I've a problem with the excellent cycle plugin on this site: http://www.closeinternational.com

The activeSlide class for the pager doesn't seem to want to change although everything else is working. I'm using version 2.88.

**Comment by damonbauer** [comment]
Check http://jquery.malsup.com/cycle/options.html for an option called "ActivePagerClass".  Do you have that in your call?

**Comment by pixedelic** [comment]
Hi, I've the same problem with IE... activeSlide class is associated at the wrong slide, but only with IE.
I tested the Version: 2.63 and it's ok. The problem is with the last version (Version: 2.88)...

**Comment by malsup** [comment]
Test page?

**Comment by malsup** [comment]
Seems to be working on your page:  http://www.closeinternational.com/
