### ISSUE TITLE
Slideshow should work with less than 2 images

### ISSUE THREAD

**Issue by alper** [malsup/cycle#24]
When retrieving images dynamically the 2 images minimum is a significant limitation.

With 1 image, the slideshow should work too, that image being static (like a splash).
With 0 images, the slideshow should work too, waiting for images to be added.

**Comment by malsup** [comment]
What exactly does "work" mean with a one-image slideshow?  How is it not working now?
Regarding waiting for images to be added, I'd suggest waiting to initialize the slideshow instead.
