### ISSUE TITLE
Feature Request: $(...).cylce({next: "this"})

### ISSUE THREAD

**Issue by killercup** [malsup/cycle#3]
Just another idea I had lately: When dealing with more than one instance on the same page (maybe even all inside some ".slideshow" ;), it would be quite cool to chose the slideshow itself as trigger for the "next"/"prev" options instead of some element (because this is some kind of confusing when every .slideshow has a .next…).

Even more cool would be of course support for some syntax like "this ~ .next" (.next in the same div as the slideshow itself), this would make 1000 cycles on one page work like a charm. :)

**Comment by malsup** [comment]
Already supported via each loop.  (http://www.malsup.com/jquery/cycle/multi3.html)
