### ISSUE TITLE
v2.81+ a.activeSlide

### ISSUE THREAD

**Issue by butchewing** [malsup/cycle#30]
After v2.80 a.activeSlide does recognize CSS change (ie. a.activeSlide {color:#fff})

**Comment by malsup** [comment]
activeSlide is now set on immediate children of the pager only.  So if your pager markup looks like this:

```
<li><a href="#">Slide 1</a></li>
```

Then your CSS rule would be something like this:

```
li.activeSlide a { background-color: red }
```
