### ISSUE TITLE
Document possibility to send non-selectors as pager option

### ISSUE THREAD

**Issue by voxpelli** [malsup/cycle#32]
As the title says - the pager option is currently documented on http://jquery.malsup.com/cycle/options.html to be a selector, but since it is only used in a $() one can equally well set it to a jQuery object. Sending a jQuery object might be easier if you have multiple cycles on a single page since then you don't have to create unique id:s for each one of them.

**Comment by malsup** [comment]
Page updated.  Please note that nothing about using a selector string implies unique ids.
