### ISSUE TITLE
Cycle Plugin 'after' Callback - Controlls arn't hidden if there is only 1 slide.

### ISSUE THREAD

**Issue by ghost** [malsup/cycle#34]
When using the after callback from this demo:
http://jquery.malsup.com/cycle/after.html

If there is only 1 slide then both controls are shown instead of being hidden. I can understand why the plugin wasn't designed to work with only 1 slide, however if the plugin is used with a CMS then this can be the case.

**Comment by malsup** [comment]
This does work now.
