### ISSUE TITLE
Feature Request: Make ability to setup which selectors "cycle" will use and rotate

### ISSUE THREAD

**Issue by Nikita-S-Doroshenko** [malsup/cycle#35]
Hey guys,
It will be nice if you can teach "cycle" to work with only one type of selectors, for example with [a] only or with any other
example:
[div class=rotator]
      [div class=frame]
      [a href="#"]img[/a]
      [a href="#"]img[/a]
      [a href="#"]img[/a]
      [navigation][a][/a][/navigation]
[/div]

The deal, is to teach cycle select only [a] tags and rotate only them, because now, we need to wrap [a] tags in addition div blocks.

[div class=rotator]
      [div class=frame]
      [div class=slider]
            [a href="#"]img[/a]
            [a href="#"]img[/a]
            [a href="#"]img[/a]
      [/div]
      [navigation][a][/a][/navigation]
[/div]

**Comment by malsup** [comment]
Yes, you can use the slideExpr option for that.

http://jquery.malsup.com/cycle/slideExpr.html
