### ISSUE TITLE
'before' function to complete before animating to the next slide.

### ISSUE THREAD

**Issue by tbwcf** [malsup/cycle#38]
Hello - I have posted on stackoverflow - but thought this might be a better place to get help ( http://stackoverflow.com/questions/5220057/jquery-cycle-before-function-to-complete-before-animating-to-the-next-slide )

I'm using the jQuery Cycle plugin for a slider - I need to complete a function when the next link is clicked before the slider moves onto the next slide.

<pre>$('#marques-slider').cycle({
fx: 'scrollHorz',
transition: 'scrollHorz',
timeout:  0,
prev:    '#prev-slide',
    next:    '#next-slide',
    pager:   '#nav', 
    easing: 'easeInOutExpo',
    speed:  1000,
    before:  slideUp, 
    after:   slideDown,
    startingSlide: 1
});
</pre>

At present both my onBefore function and the next slide function are animating at the same time.

I also tried creating the next links outside of the plugin:

<pre>            $('#next-slide').click(function(){
                $('.marques-product-content').animate({
                    height : '0'
                }, function(){
                    $('#marques-slider').cycle('next');
                });
                return false;
            });
</pre>

but this causes some funky behaviour with the slides backfground images changing before animating and the function is only working on the first click :/

At the moment I can't see anyway to prevent the next action firing before the 'before' function is complete. I'm using the code below.

**Comment by malsup** [comment]
My suggestion would be to not use cycle's "before" and "next" options and rather bind your own callback fn to the click event of #next-slide.  In that callback, run your desired animation and then manually trigger the next slide transition like this:

```
$('#marques-slider').cycle('next');
```
