### ISSUE TITLE
Options Reference

### ISSUE THREAD

**Issue by Emuentes** [malsup/cycle#40]
My issue is with the documentation located at http://jquery.malsup.com/cycle/options.html

It says, "activePagerClass: 'activeSlide', // class name used for the active pager link"

It should say, "activePagerClass: 'activeSlide', // class name used for the active pager li element"

This typo causes confusion as in the thread below.
http://forum.jquery.com/topic/jquery-cycle-activepagerclass-assigned-to-wrong-element

The solution Malsup proposed in the thread over the confusion doesn't work in my case.
I found a workaround for my issue though.

**Comment by malsup** [comment]
Fixed. Changed to "active pager element".
