### ISSUE TITLE
Feature Request - Grab Image SRC from Link HREF Attributes

### ISSUE THREAD

**Issue by kcrwfrd** [malsup/cycle#41]
Having a large number of `<IMG>` elements in your markup slows down loading other parts of the page (specifically images in CSS, and _especially_ in IE). Consequentially, even though from the ~2nd slide onwards they don't need to be immediately visible, they can slow down the loading of the rest of the site.

It would be really cool if there was an option in Cycle that allowed you to markup the slideshow using `<A>` tags with the `<IMG>` SRC attribute in their HREF attributes. Then cycle would automatically preload the files and insert the `<IMG>` tags for the slideshow. This can be done manually, but it'd be nice if it was a feature/option included in Cycle.

**Comment by malsup** [comment]
I think this is one that's better off left for manual scripting as each situation would likely be slightly different and you're really only talking about something like four lines of code:

```
$('#slideshow > a').each(function() {
    var $this = $(this), src = $this.attr('href');
    this.append('<img src="'+src+'" width=200 height=200>');
});
```
