### ISSUE TITLE
Anchor tags broken in cycle.lite

### ISSUE THREAD

**Issue by jessehs** [malsup/cycle#43]
Cycling through anchor tags with images embedded in them results in every slide linking to one of the slide's link path, and not the others. (I think it's "example.com/3" in the example below. I'm not sure whether it's the first or last...)

ex:

<div id="slideshow">
  <a href="example.com/1"><img src="example1.jpg" /></a>
  <a href="example.com/2"><img src="example2.jpg" /></a>
  <a href="example.com/3"><img src="example3.jpg" /></a>
</div>

Switching to the regular jquery.cycle.min.js fixes this problem.

Perhaps this has to do with the "display: none;" style not being dynamically applied to each inactive slide, as I've noticed that jquery.cycle.lite does not do this, but jquery.cycle.min does do this.

**Comment by malsup** [comment]
Fixed.
