### ISSUE TITLE
pause on hover reversed

### ISSUE THREAD

**Issue by superbia** [malsup/cycle#44]
When the cursor is over the cycle on initial page load the pause on hover option becomes reversed. Moving the cursor off the cycle resumes the cycle and vice versa.

On line 296, changing `this.cyclePause++;` to equal true and `this.cyclePause++;` to equal false fixed the problem for me. I did the same for pauseOnPagerHover on line 777.

**Comment by malsup** [comment]
Fixed.  Next update will have a change to handle this.
