### ISSUE TITLE
Delay on last slide, redirect after last slide

### ISSUE THREAD

**Issue by naught101** [malsup/cycle#5]
Over at drupal, we're trying to get a couple of new features into a module that uses this (very nice) plugin: http://drupal.org/node/515356

Specifically, the option to delay the slideshow on the last slide (or manually specify the delay on the last slide). It might also be good to allow a manually delay over ride on an arbitrary nth slide, dunno

And the option to redirect the browser to a given URL after the slide show has run through once.

Are these features that you think would be good to have in core Cycle Plugin, or should we just add them on to the drupal module version?

**Comment by malsup** [comment]
You can use the 'timeoutFn' option to control the timeout values of every slide.  Demo here:

http://www.malsup.com/jquery/cycle/timeout2.html

To redir the browser after the last slide you can use the 'end' callback (along with autostop:true).

**Comment by naught101** [comment]
sweet, thanks. I'll have a crack at that.
