### ISSUE TITLE
Fade out previous slide before fade in next slide

### ISSUE THREAD

**Issue by reformatco** [malsup/cycle#50]
Is there a way to fade out the previous slide to the background color then fade in the next slide. I know this isn't an issue to apologies, just a question. 

I have used your plugin for full screen images (instead of say something like supersized) and fading the previous before the next one would improve performance considerably for this.

**Comment by malsup** [comment]
Try setting the 'sync' option to false:

```
sync: false
```

**Comment by reformatco** [comment]
Sorry for the numptiness. This is exactly what i want, thanks so much
