### ISSUE TITLE
Padding issue

### ISSUE THREAD

**Issue by DannyJoris** [malsup/cycle#53]
Hello Mike,

Thanks for your excellent module.

I'm using the Drupal views_slideshow module (6.x-2.x), which uses the cycle plugin, and I have an issue with padding of thumbnail tabs. I've talked to the maintainer rednahead and he has no idea why it happens or how to solve it.

Basically if I add no padding hovering to active the slide works nice. If I add a little bit of padding, when hovering it skips the sliding effects - it just skips/blinks instead. There is no smooth effect. Ironically, if I use an overload of padding, it works really smooth if I only hover/touch the padding areas.

I've explained the issue here. I've set up two demo sites. http://drupal.org/node/1239586#comment-4825678

Thanks in advance.

Cheers,
Danny

**Comment by DannyJoris** [comment]
I meant excellent plugin! :)

**Comment by DannyJoris** [comment]
http://d6theming-small.dannyjoris.ca/viewsslideshow1 : without padding: works fine
http://d6theming-small.dannyjoris.ca/viewsslideshow2 : with 5px padding: skips the effect
http://d6theming-small.dannyjoris.ca/viewsslideshow3 : with lots of padding: If you hover over the padding areas only it works fine, but if you start hitting the views fields, then it skips...

**Comment by malsup** [comment]
Fixed.  http://malsup.github.com/jquery.cycle.all.js

**Comment by DannyJoris** [comment]
It works well now. Thanks !!
