### ISSUE TITLE
Is it possible to set a different duration for individual images to be visible during a slideshow?

### ISSUE THREAD

**Issue by westwind79** [malsup/cycle#54]
I was trying to set a different duration between animations for each slide. I saw in the functions that you have:

timeoutFn:     null,  // callback for determining per-slide timeout value:  function(currSlideElement, nextSlideElement, options, forwardFlag) 

can you explain to me if and how it would be possible if there are 5 slides to make the first slide visible for 20seconds and another 8 sec and then maybe 5sec for the rest? 

Any info would be much appreciated!
- Noah

**Comment by bdukes** [comment]
There are demos of this in action at http://jquery.malsup.com/cycle/timeout.html and http://jquery.malsup.com/cycle/timeout2.html

**Comment by westwind79** [comment]
OMG you just saved my life!
