### ISSUE TITLE
Sychronization on prev/next between slideshows on the same page

### ISSUE THREAD

**Issue by lucipacurar** [malsup/cycle#55]
Hi,

I have an issue. I have two slideshows on my page: one at the bottom which gets initialized at document ready, and one at the top which get displayed and initialized when clicking on an menu element. Both of those have prev/next buttons.

When I load the page, trigger the top slideshow and navigating through it with the prev/next controls, the slideshow at the bottom of the page does the same thing, just like they're connected somehow. If I destroy the top slideshow and initialize it again the issue goes away.

Any idea what could it be?

Thanks,
Lucian

**Comment by malsup** [comment]
Sounds like you're using the same elements as prev/next controls for both slideshows.  The prev and next option values are intended to be jQuery selector strings, so you can get as clever as you need to in order to avoid this type of thing.
