### ISSUE TITLE
aspect doesn't work

### ISSUE THREAD

**Issue by kf420** [malsup/cycle#59]
I tried both cycle.all v2.9995 and cycle.lite v1.3, and none seem to render the "aspect" option correctly.

The below stretches image to 800x800 instead of resizing according to aspect ratio and cropping:
$('div').cycle({ width: 800, height: 800, fit: true, aspect: true, center: true });

**Comment by malsup** [comment]
Try w/o the height option and set width/height attributes on your images.  If you provide both width and height then that's what you'll get.  Also, cycle lite does not support the aspect option.
