### ISSUE TITLE
Pager activeSlide "disconnected" after $.load and $.cycle re-init

### ISSUE THREAD

**Issue by bryanbuchs** [malsup/cycle#6]
I'm fetching a block of markup to use with $.cycle, using the $.load() function with a callback to do the init. On the first load, everything looks and works great. 

However, when using the 'pager' option, things get a little weird when trying to empty and load/reload another block of html. The slides continue to run in sequence, but the activeSlide pager doesn't match the current slide. I can't quite identify the pattern --  sometimes the pager skips back then forwards, sometimes it's just off by a few numbers. 

Demo: http://www.kapow.com/cycle/

Is there a method to "destroy" the cycle object? I've tried unbind(), die(), remove(), empty()...

**Comment by malsup** [comment]
The destroy method is coming very soon.

**Comment by malsup** [comment]
destroy function landed in v2.80.  Demo:

http://jquery.malsup.com/cycle/destroy.html

**Comment by bryanbuchs** [comment]
Thanks Mike, you're awesome. Looks like 'destroy' was relatively simple, kicking myself for not forking and fixing. I just couldn't track down where the bind()'s were happening.
