### ISSUE TITLE
Cycle stops after tab change with jQuery 1.6.2

### ISSUE THREAD

**Issue by nxtd** [malsup/cycle#64]
Hey,

I am using jQuery 1.6.2 and I have a problem with the plugin stoping to 'cycle' when I change tabs in the browser, wait a little and change back to the page containing the slideshow.
I have checked your examples and seemed I was doing everything right.
Tried a workaround with pause/resume on window focus/blur without success.
Then I changed the jQuery to 1.5 as I saw you were using this version on your page and it worked.
Hope you can fix this.

Cheers and thanks for your plugin!

**Comment by malsup** [comment]
Have you tried jQuery 1.6.3?

**Comment by nxtd** [comment]
Nope, but will definitely do tomorrow :)

**Comment by shshaw** [comment]
I had a similar issue with Cycle. Rotation stops when the following happens:
- Page stays open for an extended period of time
- Page loses focus (background tab, etc.) for short periods of time. It doesn't stop consistently on the same item, but appears to stop after a few cycles once the page has lost focus. Seems like 15-20 seconds of lost focus is all it needs.

I've now switched from jQuery 1.6.0 to 1.6.3 and then 1.6.4 with no differences.

Issues happen both in Firefox 6 & Chrome 14 Dev.

**Comment by nxtd** [comment]
I forgot to reply here to say that switching to 1.6.4 had fixed the issue for me.
