### ISSUE TITLE
'fxFn' option doesn't work

### ISSUE THREAD

**Issue by tsarasua** [malsup/cycle#7]
I'm trying to control slide effect dynamically but it seems that 'fxFn' option doesn't work.

**Comment by malsup** [comment]
Can you post a link or something?  fxFn is used by the shuffle effect, so I know that it works.

**Comment by tsarasua** [comment]
I'm sorry! Probably I misunderstood the way the fxFn option works. What I'm trying to do is a "per slide" effect control, setting the option 'fx' dynamically. Finally, I have managed to control the effect setting the option "fx" into"before" transition callback.

**Comment by malsup** [comment]
You can also declare multiple effects like this:

```
fx: 'scrollUp,turnDown,zoom,fade'
```
