### ISSUE TITLE
Posh new transition effects?

### ISSUE THREAD

**Issue by voodoo6** [malsup/cycle#70]
It would be great to add some of the posh new transitions that are appearing these days. Cycle is by far the most adaptable and versatile plugin of its type, though is starting to show it's age with the current choices of transition effects compared to the new kids on the block..

http://codecanyon.net/item/html5-image-transitions-jquery-plugin/full_screen_preview/571431
http://pixelentity.com/previews/components/estro/index.html
http://nivo.dev7studios.com/demos/

Any thoughts?

**Comment by malsup** [comment]
Yes, this is definitely on my list of things to do.  Although these new effects will probably land in cycle2.

**Comment by voodoo6** [comment]
Good to hear! Now just the question of the wait - is cycle2 a matter of months or years away? ;-)

**Comment by malsup** [comment]
Haha, that's a good question.  I'd like to think months.  :-)
