### ISSUE TITLE
"resume" command broken.

### ISSUE THREAD

**Issue by keeganbrown** [malsup/cycle#71]
Looks like it just quit working. 
Cycle Version 2.9996

Example of this behavior can be found right on one of the cycle demos: http://jquery.malsup.com/cycle/pause.html

Tested in Chrome 14 + Firefox 7

**Comment by mpettitt** [comment]
Looks like it has broken the resume for pause-on-hover as well, which is probably the same code. Works with 2.9995, never resumes on 2.9996

**Comment by malsup** [comment]
Thanks for the report.  It's fixed now.
