### ISSUE TITLE
The 'Timeouts' are not cleared if the page changes using AJAX

### ISSUE THREAD

**Issue by nefy** [malsup/cycle#74]
It appears that the timeout events are not cleared when "leaving" and "coming back" to a page using AJAX.  
The only solution i have found yet is to make a global array to store the "Timeouts" and clean them all every time i go to another page.
I am sure there can be a prettier way to do this but i will let you solve this one out :) cheers

**Comment by malsup** [comment]
When you load content that replaces a slideshow you should first 'destroy' the slideshow:

```
$('#slideshow').cycle('destroy');
```

**Comment by nefy** [comment]
_nods_ i have tried that but it didnt realy work. The "go" function should in any way recheck if the slideshow exists before re-adding the Timeout.
