### ISSUE TITLE
random option not randomizing the first image

### ISSUE THREAD

**Issue by nunoarruda** [malsup/cycle#79]
Hi,

I'm using jQuery 1.7 and cycle 2.9998 (Full plugin with all the transition effects).

I've found out that the random option is not randomizing the first image. After the first image the random seems to work fine. 

Here's an example: http://www.anfibios.net/srpcba/

I hope you fix this soon.

Thanks in advance.

Keep up the good work, cycle is a great plugin.

Nuno Arruda

**Comment by malsup** [comment]
I think v2.9999 fixes this.

**Comment by nunoarruda** [comment]
yes it does! Thanks
